--- #YAML:1.0
name:                Catalyst-Authentication-Store-Jifty-DBI
version:             0.01
abstract:            A storage class for Catalyst Authentication using Jifty::DBI
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst::Model::Jifty::DBI:   0.05
    Catalyst::Plugin::Authentication: 0.10005
    Catalyst::Runtime:             5.70
    Scalar::Util:                  0
    Test::More:                    0.47
    Test::UseAllModules:           0.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
